export interface UsuarioModel {
    tipoPersona ?: number;
    rucSunat    ?: string;
    numDocAdic  ?: string;
    razonSocial ?: string;
    estContr    ?: string;
    condDomi    ?: string;
    tipoVia     ?: string;
    nombVia     ?: string;
    numDomic    ?: string;
    intDomic    ?: string;
    loteDomic   ?: string;
    departamento?: string;
    mznDomic    ?: string;
    kmDomic     ?: string;
    ubigeo      ?: string;
    nombViaFC   ?: string;
    numFC ?: string;
    intFC ?: string;
    loteFC ?: string;
    mznaFC ?: string;
    kmFC ?: string;
    dptoFC ?: string;
    provFC ?: string;
    distFC ?: string;
    rznSocFC ?: string;
    denomComFC ?: string;
    ciiuFC ?: string;
    expFC ?: string;
    roleFc ?: string;
    powerFC ?: string;
}